package:
  name: "openstructure"
  version: "2.11.1"

source:
  path: ../.
  use_gitignore: true # note: defaults to true

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cython
    - openmm
    - numpy >=1.24,<2.0.0
    - pybind11
    - python
    - libboost
    - libboost-devel
    - libboost-python
    - libboost-python-devel
    - cmake
    - make
    - eigen
    - sqlite
    - fftw
    - zlib
    - libpng
    - libtiff
    - doxygen
    - wget
    - sysroot_linux-64 ==2.17

  host:
    - python
    - numpy >=1.24,<2.0.0
    - libboost
    - libpng
    - libtiff
    - cython
    - openmm
    - zlib
    - sqlite

  run:
    - python
    - ${{ pin_compatible('numpy') }}
    - ${{ pin_compatible('libboost', exact=True) }}
    - ${{ pin_compatible('libboost-python', exact=True) }}
    - libpng
    - openmm
    - libtiff
    - zlib
    - sqlite
    - fftw

tests:
  - python: 
      imports:
        - ost
        
about:
  homepage: https://www.openstructure.org
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Open-Source Computational Structural Biology Framework
  description: |
    This project aims to provide an open-source, modular, flexible,
    molecular modelling and visualization environment. It is targeted
    at interested method developers in the field of structural bioinformatics.
